# Generated by Django 4.2.6 on 2024-08-09 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_seeding_example', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daughter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Father',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mother',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Son',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_seeding_example.father')),
            ],
        ),
        migrations.CreateModel(
            name='Grandson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('parentage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_seeding_example.daughter')),
            ],
        ),
        migrations.AddField(
            model_name='daughter',
            name='father',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_seeding_example.father'),
        ),
        migrations.AddField(
            model_name='daughter',
            name='mother',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_seeding_example.mother'),
        ),
        migrations.AddConstraint(
            model_name='daughter',
            constraint=models.UniqueConstraint(fields=('name', 'father', 'mother'), name='unique_parentage'),
        ),
    ]
