# Generated by Django 4.0 on 2024-09-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_seeding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedseeder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='appliedseeder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
